# Generated by Django 4.0.4 on 2022-04-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
    ]
