# Generated by Django 4.0.4 on 2022-05-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagenLogo',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='logo')),
            ],
        ),
    ]
