# Generated by Django 4.0.4 on 2022-04-24 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_producto_stock'),
    ]

    operations = [
    ]
