# Generated by Django 4.0.4 on 2022-05-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_imagenlogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenlogo',
            old_name='id_producto',
            new_name='id_imagen',
        ),
    ]
