# Generated by Django 4.0.4 on 2022-05-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_id_producto_imagenlogo_id_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenlogo',
            name='nombre',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
