# Generated by Django 4.0.4 on 2022-04-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0003_remove_producto_proveedor_remove_producto_categoria_and_more'),
    ]

    operations = [
    ]