# Generated by Django 4.0.4 on 2022-04-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0003_remove_producto_proveedor_remove_producto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=30)),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.region')),
            ],
        ),
    ]
