# Generated by Django 4.0.4 on 2022-05-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_imagenlogo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenlogo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='imagenlogo',
            name='descripcion',
            field=models.CharField(default='sjsja', max_length=310),
            preserve_default=False,
        ),
    ]
