# Generated by Django 4.0.4 on 2022-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_imagenlogo_nombre_imagenlogo_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion1',
            fields=[
                ('id_presentacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=310)),
                ('imagen', models.ImageField(null=True, upload_to='logo')),
            ],
        ),
        migrations.AlterField(
            model_name='imagenlogo',
            name='descripcion',
            field=models.TextField(max_length=310),
        ),
    ]
