# Generated by Django 4.0.4 on 2022-05-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_presentacion1_alter_imagenlogo_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion2',
            fields=[
                ('id_presentacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=310)),
                ('imagen', models.ImageField(null=True, upload_to='logo')),
            ],
        ),
    ]
