# Generated by Django 4.0.4 on 2022-05-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_presentacion2'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenlogo',
            name='titulo',
            field=models.CharField(default='titulo', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentacion1',
            name='titulo',
            field=models.CharField(default='titulo', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentacion2',
            name='titulo',
            field=models.CharField(default='ajaj', max_length=20),
            preserve_default=False,
        ),
    ]
