# Generated by Django 4.0.4 on 2022-05-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_presentacion3_delete_imagenlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion1',
            name='ubicacion_img',
            field=models.TextField(default='Derecha', max_length=20),
        ),
        migrations.AlterField(
            model_name='presentacion1',
            name='descripcion',
            field=models.TextField(max_length=410),
        ),
        migrations.AlterField(
            model_name='presentacion2',
            name='descripcion',
            field=models.TextField(max_length=410),
        ),
        migrations.AlterField(
            model_name='presentacion3',
            name='descripcion',
            field=models.TextField(max_length=410),
        ),
    ]
