/*CREACION DE USUARIO*/
CREATE USER ODYSSEY_BD IDENTIFIED BY "oraodypass22"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER ODYSSEY_BD QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO ODYSSEY_BD;
GRANT "RESOURCE" TO ODYSSEY_BD;
ALTER USER ODYSSEY_BD DEFAULT ROLE "RESOURCE";