# Generated by Django 4.0.4 on 2022-05-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='dv',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rut',
            field=models.IntegerField(null=True),
        ),
    ]
