# Generated by Django 4.0.4 on 2022-04-29 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='id',
            new_name='id_categoria',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(default='descripcion generica', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='producto.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='id_producto',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='id_proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='producto.proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.pais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=70),
        ),
    ]
