# Generated by Django 4.0.4 on 2022-05-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cant_cuotas', models.IntegerField(null=True)),
                ('monto_cuotas', models.IntegerField(null=True)),
                ('estado', models.CharField(default='Pedido en preparacion', max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Pago',
            fields=[
                ('id_tipo_pago', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_compra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('precio_producto', models.IntegerField()),
                ('cantidad', models.IntegerField(null=True)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
