# Generated by Django 4.0.4 on 2022-05-07 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producto', '0002_rename_id_categoria_id_categoria_and_more'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro_id', models.CharField(max_length=100, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ManyToManyField(to='producto.producto')),
                ('rut_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
