# Generated by Django 4.0.4 on 2022-05-21 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='id_direccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='id_tipo_pago',
            field=models.ForeignKey(default='VA', on_delete=django.db.models.deletion.CASCADE, to='carrito.tipo_pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='rut_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle_compra',
            name='rut_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
