# Generated by Django 4.0.4 on 2022-05-05 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_carrito_carro_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='subTotal',
            new_name='subtotal',
        ),
    ]
