# Generated by Django 4.0.4 on 2022-05-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_compra_tipo_pago_delete_carrito_compra_id_pago_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='id_direccion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_pago_pago',
            field=models.CharField(max_length=3),
        ),
    ]
