# Generated by Django 4.0.4 on 2022-05-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_alter_compra_id_direccion_alter_compra_id_pago_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_pago',
            name='id_tipo_pago',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
