# Generated by Django 4.0.4 on 2022-05-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_alter_tipo_pago_id_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_compra',
            name='id_compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carrito.compra'),
            preserve_default=False,
        ),
    ]
