# Generated by Django 4.0.4 on 2022-05-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_detalle_compra_id_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='id_pago_pago',
        ),
        migrations.AddField(
            model_name='compra',
            name='id_tipo_pago',
            field=models.ForeignKey(default='VD', on_delete=django.db.models.deletion.CASCADE, to='carrito.tipo_pago'),
            preserve_default=False,
        ),
    ]
