# Generated by Django 4.0.4 on 2022-05-11 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usuario_correo'),
        ('carrito', '0007_remove_compra_id_pago_pago_compra_id_tipo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='id_direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.direccion'),
        ),
    ]
