# Generated by Django 4.0.4 on 2022-05-16 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_rename_id_categoria_id_categoria_and_more'),
        ('carrito', '0008_alter_compra_id_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_compra',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
        ),
    ]
