# Generated by Django 4.0.4 on 2022-05-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0009_alter_detalle_compra_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(default='Pedido en preparacion', max_length=20),
        ),
    ]
