# Generated by Django 4.0.4 on 2022-05-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default='99'),
            preserve_default=False,
        ),
    ]
