# Generated by Django 4.0.4 on 2022-06-01 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usuario_dv_alter_usuario_rut'),
        ('user', '0003_alter_usuario_rut'),
    ]

    operations = [
    ]
