# Generated by Django 4.0.4 on 2022-05-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='principal',
            field=models.CharField(default='SI', max_length=2),
        ),
    ]
