# Generated by Django 4.0.4 on 2022-06-10 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usuario_activation_key_usuario_key_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2022, 6, 9)),
        ),
    ]
