# Generated by Django 4.0.4 on 2022-06-09 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usuario_rut'),
        ('user', '0005_usuario_activation_key_usuario_key_expires_and_more'),
    ]

    operations = [
    ]
