# Generated by Django 4.0.4 on 2022-06-12 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_usuario_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2022, 6, 11)),
        ),
    ]
