# Generated by Django 4.0.4 on 2022-06-09 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_merge_20220609_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2022, 6, 9)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
