# Generated by Django 4.0.4 on 2022-05-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioEnvio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
