# Generated by Django 4.0.4 on 2022-05-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_descuentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuentos',
            name='respuesta',
            field=models.CharField(default='2', max_length=50),
            preserve_default=False,
        ),
    ]
